### ISSUE TITLE
Upgrade the initial volume size of each chain

### ISSUE THREAD

**Issue by en** [octopus-network/octopus-webapp#96]
[code](https://github.com/octopus-network/octopus-webapp/blob/40b54a4a536c40de41750e6064f6e234f8d36151/src/config/constants.ts#L62)

debionetwork 200G
myriad 200G
atocha 120G
discovol 120G
fusotao 260G

**Comment by chezhe** [comment]
https://github.com/octopus-network/octopus-webapp/pull/97
